# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Nome', max_length=200)),
                ('shortName', models.CharField(db_column='NomeAbreviado', max_length=120, null=True)),
                ('primaryEmail', models.CharField(db_column='EmailPrincipal', max_length=120, null=True)),
                ('secondaryEmail', models.CharField(db_column='EmailSecundario', max_length=120, null=True)),
                ('cpf', models.CharField(db_column='CPF', max_length=14, null=True)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=32, null=True)),
                ('corporateName', models.CharField(db_column='RazaoSocial', max_length=200, null=True)),
                ('stateInscription', models.CharField(db_column='InscricaoEstadual', max_length=50, null=True)),
                ('municipalInscription', models.CharField(db_column='InscricaoMunicipal', max_length=50, null=True)),
                ('gender', models.IntegerField(choices=[(2, 'Male'), (1, 'Female')], db_column='Sexo', max_length=1, null=True)),
                ('maritalStatus', models.IntegerField(choices=[(0, 'Outro'), (1, 'Solteiro'), (2, 'Casado'), (3, 'Viúvo'), (4, 'Divorciado'), (5, 'União Estável')], db_column='EstadoCivil', max_length=1, null=True)),
                ('birthday', models.DateField(db_column='DataDeNascimento', null=True)),
                ('personKey', models.UUIDField(db_column='ChavePessoa', default=uuid.uuid4, editable=False)),
                ('isValid', models.BooleanField(db_column='Valido', default=True)),
                ('activationKey', models.UUIDField(db_column='ChaveAtivacao', default=uuid.uuid4, editable=False, null=True)),
                ('activationDate', models.DateTimeField(db_column='DataAtivacao')),
                ('registerDateTime', models.DateTimeField(db_column='DataHoraRegistro', default=django.utils.timezone.now, editable=False)),
                ('lastUpdateDateTime', models.DateTimeField(db_column='DataHoraUltimaAtualizacao', default=django.utils.timezone.now, editable=False)),
                ('deleteDateTime', models.DateTimeField(db_column='DataHoraExclusao', editable=False, null=True)),
                ('deleteKey', models.CharField(db_column='ChaveExclusao', max_length=64, null=True)),
                ('registerNumber', models.CharField(db_column='NumeroDeRegistro', max_length=64, null=True)),
                ('comments', models.TextField(db_column='comentarios', null=True)),
            ],
        ),
    ]
